draw_set_font(Font1)
draw_set_color(c_black)
//draw_text(0,30,"Score: " + string(max(player_score, 0)))
draw_text_transformed(1,40,"Bear Reputation",0.6,0.6,0)
draw_healthbar(8,8,556,45,reputationLeft,c_black,c_red,c_lime,0,true,true)
